### ISSUE TITLE
How many examples does one needs to finetune the model?

### ISSUE THREAD

**Issue by amankhandelia** [VikParuchuri/surya#10]
Hi Surya,

Thanks for the fantastic work, this really does work reasonably well with one of the historical dataset I am working with. Here is an example (from the proceeding of 1st Vidhan Sabha of UP)

![e9fccf5f-0fda-4dda-8efa-2ae656b6a5d1](https://github.com/VikParuchuri/surya/assets/7098967/53dfd28d-d941-4dc6-b2e8-8f4c85aeb275)

As you can see the edges overlap at times, so I was wondering if I can improve this by finetuning the underlying models, by weakly labelling it with your library and then refining the labels manually. Hence my question, can you shine some light on how many documents, did you use to train your model and how many docs do you think I might have to label to get better results?

One more request, please open up the discussions tab on this repo, that way user can showcase and help each other use this library in more effective manner

**Comment by VikParuchuri** [comment]
Before finetuning, you may want to play around with the threshold settings (in the readme).  That can help reduce overlaps.  

You may also want to upgrade the surya version `pip install -U surya-ocr`.  The new version allows for non-axis-aligned bboxes (in the `polygons` field)`.

I think this will solve the issue without finetuning.

If you want to finetune, I think a few dozen should do it if it is very task specific (these kind of documents, in this language)

**Comment by SouravaBehera** [comment]
@staru09 , @amankhandelia Did you find a way to finetune the models?

**Comment by mnwato** [comment]
Need help to finetun both det and rec model.
Any example script which declare input and output format.
Any help is appriciated
