### ISSUE TITLE
ocr error

### ISSUE THREAD

**Issue by homeant** [VikParuchuri/surya#123]
If a certain page of the current PDF is blank, the program will throw an error.

```
    for l in languages:
        assert len(l) <= settings.RECOGNITION_MAX_LANGS, f"OCR only supports up to {settings.RECOGNITION_MAX_LANGS} languages per image, you passed {l}."

```

**Comment by homeant** [comment]
<img width="897" alt="image" src="https://github.com/VikParuchuri/surya/assets/28803295/f53591b6-8130-4ffc-8bda-7a7f0c8d040a">

**Comment by VikParuchuri** [comment]
It looks like you're using an older version of marker (the code you pasted does not match your screenshot). Try upgrading

**Comment by homeant** [comment]
The latest version also has this problem

**Comment by homeant** [comment]
604eeead8cbb48cc81ad6854221d4369447460783945158.pdf

page_num 4 is error
