### ISSUE TITLE
Text Extraction

### ISSUE THREAD

**Issue by promaprogga** [VikParuchuri/surya#13]
How can I get text?

**Comment by VikParuchuri** [comment]
Text extraction is training now.  Hopefully done within 2-3 weeks.

**Comment by eswenson1** [comment]
What languages are you planning to support?

**Comment by VikParuchuri** [comment]
These ISO codes:

['af', 'am', 'ar', 'as', 'az', 'be', 'bg', 'bn', 'br', 'bs', 'ca', 'cs', 'cy', 'da', 'de', 'el', 'en', 'eo', 'es', 'et', 'eu', 'fa', 'fi', 'fr', 'fy', 'ga', 'gd', 'gl', 'gu', 'ha', 'he', 'hi', 'hr', 'hu', 'hy', 'id', 'is', 'it', 'ja', 'jv', 'ka', 'kk', 'km', 'kn', 'ko', 'ku', 'ky', 'la', 'lo', 'lt', 'lv', 'mg', 'mk', 'ml', 'mn', 'mr', 'ms', 'my', 'ne', 'nl', 'no', 'om', 'or', 'pa', 'pl', 'ps', 'pt', 'ro', 'ru', 'sa', 'sd', 'si', 'sk', 'sl', 'so', 'sq', 'sr', 'su', 'sv', 'sw', 'ta', 'te', 'th', 'tl', 'tr', 'ug', 'uk', 'ur', 'uz', 'vi', 'xh', 'yi', 'zh']

**Comment by StephennFernandes** [comment]
hey @VikParuchuri is the OCR model that was training ready ?

**Comment by VikParuchuri** [comment]
Yes, check the README
