### ISSUE TITLE
why surya-ocr model detect Arabic language text separately every letter  its should be jion every litter form of word 

### ISSUE THREAD

**Issue by haroon423** [VikParuchuri/surya#140]
surya-ocr model detect arabic text evey litter separately but its not correct its should be jion which are form word but english language text correctly its jion every words 
![surya-ocr-issue](https://github.com/VikParuchuri/surya/assets/97038384/24b6c0d5-bcd0-49c7-ab1e-1a0577adfd44)
![surya-ocr-issue](https://github.com/VikParuchuri/surya/assets/97038384/0b45807b-0205-4dcf-95cf-26693acbbb79)

**Comment by VikParuchuri** [comment]
The joining is a rendering thing.  It can OCR the characters, then you can join them.  This is just how it's rendered in the GUI interface, but you can render differently if you want, in your own code.

**Comment by haroon423** [comment]
I have used  bidi algorithm or reshape arabic for it which are jion its
words but still same result no change on it but i used these two bidi
algorithm or reshape arabic for paddle ocr here its working fine but not in
surya ocr why
