### ISSUE TITLE
cannot import segformer from surya.model.detection in ubuntu

### ISSUE THREAD

**Issue by preethamdp** [VikParuchuri/surya#149]
I was able to  run 

`from surya.model.detection import segformer `

in my windows , but not able to in ubuntu , getting 

`ImportError: cannot  import name segformer from surya.model.detection (unkown location)`

I need help ......

**Comment by zzak00** [comment]
on mac also

**Comment by VikParuchuri** [comment]
I updated the models recently, and changed the paths around.  If you see the README, you can see how to import in the newest version (`from surya.model.detection import model`)
