### ISSUE TITLE
OCR does not recognize repeated characters

### ISSUE THREAD

**Issue by fignupafya** [VikParuchuri/surya#176]
If you try using the OCR for the images with texts like "999449" it will get recognized as "9449" or etc. I thought there can be bias towards paying attention to non-repeated characters. So i tried finetuning it's decoder hoping to fix its attention mechanisms. I used 2 images 1. being the character "A" and the 2. number "999449" being the with the goal overfitting the model to see if that training can solve the issue or not. It did not fix the issue or get overfitted for 1000 epochs and for 10000 epochs as well. I tried training the model's encoder+decoder with 8 images model can not recognize correctly and 2 images model can recognize correctly. The issue was not resolved again. 

Here are some logs:

[log5-encoder-decoder-10-images.txt](https://github.com/user-attachments/files/16626225/log5-encoder-decoder-10-images.txt)
[log.txt](https://github.com/user-attachments/files/16626220/log.txt)
[log2.txt](https://github.com/user-attachments/files/16626221/log2.txt)
[log3.txt](https://github.com/user-attachments/files/16626222/log3.txt)
[log4.txt](https://github.com/user-attachments/files/16626223/log4.txt)

Note: Keep in mind that I don't have deep understanding and knowledge about ai & machine learning yet but the ocr results are not correct for sure.

**Comment by VikParuchuri** [comment]
Do you have a test image?  I just updated the OCR model, which may fix this

**Comment by fignupafya** [comment]
Yes the update fixed it! May I ask what did you change and why please? I am spent some time on it but I could not get any result :/  These were some of the images i was testing with btw. 
![1](https://github.com/user-attachments/assets/8a702ab2-7223-4bfb-89d1-b1aa8062bedc)
![10](https://github.com/user-attachments/assets/b2d816b6-c959-40a6-b0d7-901ccaff48fb)

**Comment by VikParuchuri** [comment]
I changed a bunch architecturally, but I think improving the usable and full resolution of the encoder was the most likely fix
