### ISSUE TITLE
Notebook?

### ISSUE THREAD

**Issue by andysingal** [VikParuchuri/surya#2]
Hey Surya,
    Would be nice to have a notebook + store into json/parquet to be displayed using pandas/polars.
Thanks,
Andy

**Comment by Aeyxen** [comment]
See the description on this video, this guy has setup a Colab: https://www.youtube.com/watch?v=cBdZcXw44zs

**Comment by VikParuchuri** [comment]
Will merge a demo gradio app as well shortly
