### ISSUE TITLE
可以提供HTTP API的接口么

### ISSUE THREAD

**Issue by llm163520** [VikParuchuri/surya#209]
可以提供HTTP API的接口么

**Comment by wenerme** [comment]
This is my simple API wrapper

https://github.com/wenerme/dockerfiles/tree/master/ml/surya-ocr


```bash
docker run --rm -it \
  -p 3000:3000 \
  -v /data/cache:/root/.cache/ \
  --name surya-ocr quay.io/wener/surya-ocr:latest

curl -X POST -F "images=@table.png" http://localhost:3050/tabled
```

**Comment by wenerme** [comment]
> > This is my simple API wrapper
> > https://github.com/wenerme/dockerfiles/tree/master/ml/surya-ocr
> > ```shell
> > docker run --rm -it \
> >   -p 3000:3000 \
> >   -v /data/cache:/root/.cache/ \
> >   --name surya-ocr quay.io/wener/surya-ocr:latest
> > 
> > curl -X POST -F "images=@table.png" http://localhost:3050/tabled
> > ```
> 
> 1、该示例端口是否不太对？应该是3000吧； 2、有更完整的api参数介绍么？

make dev 是3050
/openapi.json 有fastapi 生成的文档

**Comment by llm163520** [comment]
感谢！

**Comment by Coinhexa** [comment]
@llm163520 @wenerme any ideas how to modify this to make it run on CPU instead of CUDA, running it on an apple m1 machine here

**Comment by wenerme** [comment]
> [@llm163520](https://github.com/llm163520) [@wenerme](https://github.com/wenerme) any ideas how to modify this to make it run on CPU instead of CUDA, running it on an apple m1 machine here


My image should works on cpu
