### ISSUE TITLE
docker install http api无法访问

### ISSUE THREAD

**Issue by llm163520** [VikParuchuri/surya#232]
关联问题：https://github.com/VikParuchuri/surya/issues/209
部署示例：
![image](https://github.com/user-attachments/assets/784af640-2a8f-4ca0-aeed-8121b962fc4c)
错误截图：
![image](https://github.com/user-attachments/assets/526e696e-ed61-4982-b7bf-7d8c973a3b4d)

**Comment by VikParuchuri** [comment]
Looks like you don't have access to huggingface - maybe a firewall issue

**Comment by llm163520** [comment]
> Looks like you don't have access to huggingface - maybe a firewall issue

docker package Is there a full version

**Comment by llm163520** [comment]
> Looks like you don't have access to huggingface - maybe a firewall issue



> > Looks like you don't have access to huggingface - maybe a firewall issue
> 
> docker package Is there a full version

Offline full version
