### ISSUE TITLE
Response time

### ISSUE THREAD

**Issue by MosbehBarhoumi** [VikParuchuri/surya#244]
Not an issue but a question: I'm trying Surya for the first time, and it seems much slower than Tesseract and PaddleOCR on the CPU. Is this normal behavior, or am I missing something?

**Comment by benhachy** [comment]
Yes, that is normal behavior, Surya is designed to be used in GPU, and would be very slow in CPU. So don't forget to load Surya models into GPU. And if you get an OOM Error, this may be useful: https://github.com/VikParuchuri/surya/issues/62
