### ISSUE TITLE
OCR seems to miss recognizing the same text, despite looking reasonable

### ISSUE THREAD

**Issue by eswenson1** [VikParuchuri/surya#27]
I've tried to OCR the attached document (first page) multiple times with various versions (0.2.0, 0.2.1, master, dev) and always get the same result -- which misses a couple lines of text in the OCR phase.  See the attached PDF (first page) and attach screenshot of the results.

[AIM-161A.pdf](https://github.com/VikParuchuri/surya/files/14270996/AIM-161A.pdf)
![Screenshot 2024-02-13 at 10 54 34 AM](https://github.com/VikParuchuri/surya/assets/867939/8ccd96b7-87bd-4b1e-99fd-4c19bb1e92e9)

**Comment by VikParuchuri** [comment]
Works for me with a new model checkpoint.  Give me a little bit to test, then will push the new checkpoint up (it will auto-download):
<img width="1826" alt="image" src="https://github.com/VikParuchuri/surya/assets/913340/81432471-f2be-471b-9b19-44388ec3085f">

**Comment by VikParuchuri** [comment]
Pushed, new checkpoint looks better all-around

**Comment by eswenson1** [comment]
Thanks. I’ll give it a try.

**Comment by eswenson1** [comment]
What branch did you push to? I didn’t see new commits on dev or master branch (github claims last commits were > 6 hours ago).

**Comment by eswenson1** [comment]
I guess the models are elsewhere and download. I restarted the GUI and it is downloading models now. I’l retest when they get downloaded (taking a long time).

**Comment by eswenson1** [comment]
Ok. Yes, this is much better. How come the OCR Result pane shows different fonts/sizes sometimes?

See my original screenshot for an example. Even with your latest model update, while the OCR recognition is much better, the rendering in the GUI shows multiple different font sizes.
