### ISSUE TITLE
OCR not detecting incorrect lines

### ISSUE THREAD

**Issue by sathish331977** [VikParuchuri/surya#33]
Can this recognition be improved. 
Detect results are as follows
![image](https://github.com/VikParuchuri/surya/assets/7473483/6464f1c9-e1af-44f5-be2c-730f7f395e28)

ocr results as follows
![image](https://github.com/VikParuchuri/surya/assets/7473483/1822916b-9968-4299-9071-a6bcba2f68b1)

**Comment by VikParuchuri** [comment]
What exactly is the problem here?  The OCR looks to be completely correct

**Comment by VikParuchuri** [comment]
I think you may want the lines sorted in reading order.  That is different from OCR - OCR is about recognizing the text.  I did add some basic sorting in the latest release, which will work in many cases.  But for more advanced sorting, look at [marker](https://github.com/VikParuchuri/marker).

**Comment by sathish331977** [comment]
Thank you, I will have a look at the marker
