### ISSUE TITLE
Extracting and saving images using the bounding box info

### ISSUE THREAD

**Issue by DeepaMahm** [VikParuchuri/surya#36]
Hello @VikParuchuri ,

Thanks for the great package.

Can the images in a pdf be saved separately using the bounding box coordinate information?

I tried the --images flag. I noticed it saves each of the page in the pdf as an image i.e. the text in each page and the image in a given page is ignored.

I would like to know if there is an option to save the figures as well.
Thanks,
Deepa

**Comment by DeepaMahm** [comment]
Hi @VikParuchuri ,
This is  a kind reminder

**Comment by VikParuchuri** [comment]
The marker library can do this - https://github.com/VikParuchuri/marker
