### ISSUE TITLE
[Feature Request] Add language: Te Reo Māori

### ISSUE THREAD

**Issue by jadebarclay** [VikParuchuri/surya#40]
Can Surya detect/OCR Te Reo Māori?

What is needed to make this possible?

**Comment by VikParuchuri** [comment]
It can detect, but not OCR.  You would need to finetune the model using Te Reo Māori text.  I don't have a simple script for finetuning now, but will make one in the future.  

The keys to finetuning are:

 - Prepare your dataset - you need text/image pairs, ideally single lines
 - Add a new language to the config (need to change the config on the model itself), and also edit surya/languages.py
 - Freeze all weights of the model except the MoE expert for the language you're training.  (set requires_grad to False)
 - Train

Not a lot of code to implement this if you want to do it yourself before I make a script.

**Comment by staru09** [comment]
> Can Surya detect/OCR Te Reo Māori?
> 
> What is needed to make this possible?

Hey @jadebarclay have you wrote the training script if not then we can write together 
if you are interested just ping me at arusharmazxx000@gmail.com and we can get it done.

**Comment by Rajucpgn** [comment]
can we expand in fine tunning for nepali handwritting
