### ISSUE TITLE
Using Surya along with "marker" to get a formatted md file as output

### ISSUE THREAD

**Issue by trivikramak** [VikParuchuri/surya#41]
Hi,
Thanks for the wonderful project!
How can we pass the output of Surya to your other project 'marker' or other post-processing tools to get a neatly formatted md file?
Can you give some guidelines or direction to work with?

**Comment by VikParuchuri** [comment]
I will be integrating this with marker in the near future!

**Comment by kdcyberdude** [comment]
Hi @VikParuchuri, Any update on this?

Can we keep this issue open to keep track?
