### ISSUE TITLE
OOM error during inference

### ISSUE THREAD

**Issue by RethikNirmalV** [VikParuchuri/surya#56]
Hi,
I was trying to run the model on colab free tier with TPU4. I had around 45 examples for which I wanted to test out the OCR extractions. However, after a certain number of inferences (after extracting for 15 examples) it results in a Out of Memory Error.

I tried clearing the cuda cache, manually invoking garbage collection, but none worked.

Attached the code used below for reference:

```
from surya.ocr import run_ocr
from surya.model.detection.segformer import load_model as load_det_model, load_processor as load_det_processor
from surya.model.recognition.model import load_model as load_rec_model
from surya.model.recognition.processor import load_processor as load_rec_processor
import os
import gc
import time
import torch

os.environ['USE_TORCH'] = '1'
device = torch.device("cuda:0")
langs = ["en"] # Replace with your languages
det_processor, det_model = load_det_processor(), load_det_model()
rec_model, rec_processor = load_rec_model(), load_rec_processor()

for image in image_list:
    start_time = time.time()
    predictions = run_ocr([image], [langs], det_model, det_processor, rec_model, rec_processor)
    end_time = time.time()
    surya_total_time += end_time - start_time
    text = "".join([i.text for i in predictions[0].text_lines])
    del predictions
    gc.collect()
    torch.cuda.empty_cache()
    result_dict_surya[file_name] = text
```

Would really like to get some inputs on methods to get around this error. Thanks in advance

**Comment by VikParuchuri** [comment]
Try reducing the batch size, as mentioned in the readme - set the `RECOGNITION_BATCH_SIZE` and/or`DETECTOR_BATCH_SIZE` environment variables lower.  This will  reduce memory usage.  You may have to experiment a bit.

Default batch size for detection is 32, and recognition is 256.

**Comment by RethikNirmalV** [comment]
Had tried that method too previously. Tried overriding the values using environment variables. But still ended up with the same error.

Code:
```
os.environ["RECOGNITION_BATCH_SIZE"] = '2'
os.environ["DETECTOR_BATCH_SIZE"] = '2'
```
Used this code before loading the model.

**Comment by benhachy** [comment]
Hi ! 
The issue is closed but I guess it is not solved, I don't think that changing the env variables would help, as you are using the python package.

But maybe try resizing your images to (700, 1200) for example, and retry your code again. 

You can use:
```
from PIL import Image
image = Image.open(IMG_PATH).resize((width, height))
```

**Comment by benhachy** [comment]
see https://github.com/VikParuchuri/surya/issues/62, I had the same error as you. It would be due to having image with a lot of lines (like a table, each cell would be detected as a bbox (line)).

**Comment by shuiqingliu** [comment]
> Try reducing the batch size, as mentioned in the readme - set the `RECOGNITION_BATCH_SIZE` and/or`DETECTOR_BATCH_SIZE` environment variables lower. This will reduce memory usage. You may have to experiment a bit.
> 
> Default batch size for detection is 32, and recognition is 256.

Setting `RECOGNITION_BATCH_SIZE` from 256 to 32 has worked fine.
