### ISSUE TITLE
Urdu Text Does Not Get Detected

### ISSUE THREAD

**Issue by Aeyxen** [VikParuchuri/surya#6]
First things first, sincere appreciation for your outstanding work in developing this incredible AI-driven OCR library. It's a fantastic tool that holds immense potential for digital humanities, I am a student of this subject.

I started my testing with some old Urdu historical documents, and unfortunately, I didn't observe any bounding box (Bbox) detection for the Urdu text within those documents.

Subsequently, I tested it with an image that contains a mix of Hindi, English, and Urdu text. To my delight, it successfully detected the Hindi and English portions of the text. However, it only recognized one line of the Urdu text, which was less than expected. I have attached the image for your reference so that you can better understand the scenario.

![image5-602w291h_0_bbox](https://github.com/VikParuchuri/surya/assets/22558347/21718661-55af-4438-82c1-c61cd4e0a128)

**Comment by VikParuchuri** [comment]
Try the new code/model - `pip install -U surya`

**Comment by VikParuchuri** [comment]
This seems to work

<img width="344" alt="image" src="https://github.com/VikParuchuri/surya/assets/913340/9284a8ae-9858-49df-a40f-5576f53ffef1">

and

<img width="358" alt="image" src="https://github.com/VikParuchuri/surya/assets/913340/621b1840-d484-4180-adbf-93173caf8690">


You may need to experiment with the threshold settings to detect more text (see README)

**Comment by Aeyxen** [comment]
Noted with thanks
