### ISSUE TITLE
Benchmarking Open Source Models

### ISSUE THREAD

**Issue by Jain-Archit** [VikParuchuri/surya#69]
Hi, 

First of all, Kudos and congratulation for your effort. Really excited to see this work. I wanted to know if there is any benchmarking done with other open source ocr models like Paddle OCR, easyocr, Keras OCR, MMOCR. I saw a table with comparison with tesseract model. Can you please share if there is some work done on this.

**Comment by VikParuchuri** [comment]
I benchmarked against Google Cloud, results are in README.  I think tesseract + Google Cloud gives enough comparison points.  I'm happy if someone else wants to benchmark against other open source models, though

**Comment by anuragphadke** [comment]
@VikParuchuri : has anybody done benchmarking against https://developer.apple.com/documentation/vision/recognizing-text-in-images? I can do it if there's interest..
