### ISSUE TITLE
Reorder Help

### ISSUE THREAD

**Issue by rlyfun** [VikParuchuri/surya#77]
I  saw surya_order could help arrange ocr'd text, however the output specifies the bounding boxes rather than the text itself

Any way to use the order method with ocr, such that it generates our text in an ordered json?

**Comment by VikParuchuri** [comment]
Yes, just do OCR, then match the text lines to the bbox coordinates (basically find the layout bbox each text line intersects with most).  Then use the layout bbox order to sort the text lines (sort left to right top to bottom within each layout bbox, and use the reading order across layout bboxes).  There are some utilities in surya that will find intersection percentage between bboxes.
