### ISSUE TITLE
Paragraph level extraction

### ISSUE THREAD

**Issue by Tejaswgupta** [VikParuchuri/surya#82]
Firstly , great work with the project!

We are currently using tesseract to extract paragraphs from a PDF and parse/store them. I tried out Surya but couldn't find any option to get the output in terms of paragraphs? Is it possible to do so, if yes, could you point me to the right set of docs or resources necessary for such implementation.

\cc @VikParuchuri

**Comment by VikParuchuri** [comment]
Try marker - GitHub.com/vikparuchuri/marker
