### ISSUE TITLE
Overwrite of lang length guarantees assertion

### ISSUE THREAD

**Issue by Sciumo** [VikParuchuri/surya#87]
```python
        if isinstance(langs[0], str):
            langs = [langs]
```
guarantees a length of 1. ?!
Why did all_langs not get assigned langs?
https://github.com/VikParuchuri/surya/blob/ac07e7c8f5046c41804eb132479e688e8efb2611/surya/model/recognition/tokenizer.py#L90

**Comment by VikParuchuri** [comment]
Langs needs to look like:

[
   ["English", "Russian"],
   ["English"]
]

One list per input line.

If it looks like ["English", "Russian"], then we turn it into a list of lists.

**Comment by Sciumo** [comment]
Then *that* is that the assert should check.
It does not.

```python
        if isinstance(langs[0], str):
            langs = [langs]
```
is *guaranteed* to fail 
```python
        assert len(langs) == len(texts)
```
